USE [Seran Database]

CREATE TABLE [BIODATA STD]
([STD ID] INT PRIMARY KEY NOT NULL,
[STD NAME]VARCHAR(30),
[STD AGE]INT,
[STD COURSE]VARCHAR(30),
[STD PHONE]BIGINT)

SELECT * FROM [BIODATA STD]

BEGIN TRANSACTION
INSERT INTO [BIODATA STD]
VALUES
(1,'Akash',21,'Automobile',9876543210),
(2,'Arunkumar',23,'chemical',9887521000),
(3,'Saravanan',25,'Science',9965743210),
(4,'Sakthi',27,'Petroleum',9655234178),
(5,'Giri',30,'IT',9877878710)
COMMIT

BEGIN TRANSACTION;
INSERT INTO [BIODATA STD]
VALUES
(6,'Prasanth',23,'M.com',9396989520),
(7,'Pranesh',20,'BE',9777564820),
(8,'Subash',25,'Nursing',9988772010)
commit

BEGIN TRANSACTION;
UPDATE [BIODATA STD]
SET [STD COURSE]='Computer'
WHERE [STD ID]=3;


--BEGIN TRANSACTION;
--DELETE FROM [BIODATA STD] WHERE [STD ID]=7;

BEGIN TRANSACTION;
ROLLBACK;
SELECT * FROM [BIODATA STD]


BEGIN TRANSACTION;
UPDATE [BIODATA STD]
SET [STD COURSE]='Petroleum Er'
WHERE [STD ID]=4;


BEGIN TRANSACTION;
SAVE TRANSACTION  STARS;

DELETE FROM [BIODATA STD] WHERE [STD ID]=6;
SAVE TRANSACTION  DEL6;

DELETE FROM [BIODATA STD] WHERE [STD ID]=7;
SAVE TRANSACTION  DEL7;

DELETE FROM [BIODATA STD] WHERE [STD ID]=8;
SAVE TRANSACTION  DEL8;


SELECT * FROM [BIODATA STD]
ROLLBACK TRANSACTION  STARS;



--DCL COMMANDS
CREATE LOGIN SERAN WITH PASSWORD='12345'

USE [Seran Database]
CREATE USER SAA for login SERAN;

--GRANT FOR PERMISSION
GRANT SELECT,INSERT ON [dbo].[BIODATA STD] TO SAA;

--REVOKE FOR GET BACK THE PERMISSION
REVOKE SELECT,INSERT ON [Seran Database].[dbo].[BIODATA STD] FROM SAA;














